### Importing Libraries

In [1]:
import numpy as np
import pandas as pd

In [2]:
n = 10 
np.random.seed(42) 
first_name=['Alexis', 'Tira', 'Amiyah', 'Kenny', 'Makayla', 'Star', 'Tre', 'Ray', 'Yeni', 'Maddie']
last_name=['Smith', 'Johnson', 'Brown', 'Taylor', 'Anderson']
name=np.random.choice(first_name,n)+" "+np.random.choice(last_name,n) 
print(name)
ages=np.random.randint(18,26,n)
marks=np.random.randint(40,100,size=(n,5))
gender=np.random.choice(['Male', 'Female'],size=n)
print(ages)
print(marks)
student_data=pd.DataFrame(marks,columns=['Physics', 'Math', 'CS', 'English', 'History'])
student_data

['Tre Taylor' 'Kenny Brown' 'Ray Anderson' 'Makayla Johnson' 'Tre Taylor'
 'Maddie Johnson' 'Amiyah Taylor' 'Tre Anderson' 'Ray Smith'
 'Makayla Taylor']
[19 23 22 21 18 18 20 20 24 19]
[[67 99 55 54 86]
 [90 83 94 91 96]
 [42 76 90 46 60]
 [48 78 57 43 64]
 [99 53 89 97 48]
 [65 92 41 59 67]
 [86 99 46 83 47]
 [86 74 53 56 75]
 [89 79 43 41 45]
 [93 81 43 93 68]]


,Physics,Math,CS,English,History
0,67,99,55,54,86
1,90,83,94,91,96
2,42,76,90,46,60
3,48,78,57,43,64
4,99,53,89,97,48
5,65,92,41,59,67
6,86,99,46,83,47
7,86,74,53,56,75
8,89,79,43,41,45
9,93,81,43,93,68


In [3]:
student_data.insert(0,'Age',ages)

In [4]:
student_data.insert(0,'Name',name)

In [5]:
student_data.insert(2,'Gender',gender)

In [6]:
student_data

,Name,Age,Gender,Physics,Math,CS,English,History
0,Tre Taylor,19,Male,67,99,55,54,86
1,Kenny Brown,23,Female,90,83,94,91,96
2,Ray Anderson,22,Female,42,76,90,46,60
3,Makayla Johnson,21,Female,48,78,57,43,64
4,Tre Taylor,18,Female,99,53,89,97,48
5,Maddie Johnson,18,Female,65,92,41,59,67
6,Amiyah Taylor,20,Female,86,99,46,83,47
7,Tre Anderson,20,Female,86,74,53,56,75
8,Ray Smith,24,Female,89,79,43,41,45
9,Makayla Taylor,19,Male,93,81,43,93,68


In [7]:
student_data.to_csv('student_raw_data.csv',index=False)

In [8]:
pd.read_csv('student_raw_data.csv')

,Name,Age,Gender,Physics,Math,CS,English,History
0,Tre Taylor,19,Male,67,99,55,54,86
1,Kenny Brown,23,Female,90,83,94,91,96
2,Ray Anderson,22,Female,42,76,90,46,60
3,Makayla Johnson,21,Female,48,78,57,43,64
4,Tre Taylor,18,Female,99,53,89,97,48
5,Maddie Johnson,18,Female,65,92,41,59,67
6,Amiyah Taylor,20,Female,86,99,46,83,47
7,Tre Anderson,20,Female,86,74,53,56,75
8,Ray Smith,24,Female,89,79,43,41,45
9,Makayla Taylor,19,Male,93,81,43,93,68
